[package]
name = "ai-client-qianwen"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
ai-client-common.workspace = true

reqwest.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
snafu.workspace = true

[dev-dependencies]